.PHONY: clean All

All:
	@echo "----------Building project:[ tt - Debug ]----------"
	@cd "tt" && "$(MAKE)" -f  "tt.mk"
clean:
	@echo "----------Cleaning project:[ tt - Debug ]----------"
	@cd "tt" && "$(MAKE)" -f  "tt.mk" clean
